movieproject/movieapp/urls.py
from django.urls import path, include
from . import views
app_name = 'movieapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('movie/<int:movieid>/', views.detail, name='detail'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
app_name = 'movieapp'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movieapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models


# Create your models here.
class movie(models.Model):
    mname = models.CharField(max_length=250)
    mdesc = models.TextField()
    myear = models.IntegerField()
    mimg = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.mname

movieproject/movieapp/forms.py
from django import forms
from .models import movie


class movieform(forms.ModelForm):
    class Meta:
        model = movie
        fields = ['mname', 'mdesc', 'myear', 'mimg']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import movie
from .forms import movieform


def index(request):
    film = movie.objects.all()
    context = {
        'movie': film
    }
    return render(request, 'index.html', context)


def detail(request, movieid):
    movie1 = movie.objects.get(id=movieid)
    return render(request, 'detail.html', {'movie': movie1})


def add_movie(request):
    if request.method == "POST":
        mname = request.POST.get('mname', )
        mdesc = request.POST.get('mdesc', )
        myear = request.POST.get('myear', )
        mimg = request.FILES['mimg']
        mmovie = movie(mname=mname, mdesc=mdesc, myear=myear, mimg=mimg)
        mmovie.save()
    return render(request, 'add.html')


def update(request, id):
    film = movie.objects.get(id=id)
    form = movieform(request.POST or None, request.FILES, instance=film)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'film': film})


def delete(request, id):
    if request.method == 'POST':
        film = movie.objects.get(id=id)
        film.delete()
        return redirect('/')
    return render(request, 'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="mname" placeholder="Enter the Movie name"><br>
    <input type="text" name="mdesc" placeholder="Enter the Movie Description"><br>
    <input type="text" name="myear" placeholder="Enter the Movie Release year"><br>
    <input type="file" name="mimg"><br>
    <input type="submit"><br>
</form>

{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie Page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      Online Movie Website
    </a>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="post">
    {% csrf_token %}
    Are you sure you want to delete this movie??
    <input type="submit">
</form>
{% endblock %}

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
        <div class="row">
                <div class="col-md-6">
                        <img src="{{movie.mimg.url}}" width="300px" height="300px">
                </div>
                        <div class="col-md-6">
                                <h5>{{movie.mname}}</h5>
                                <h5>{{movie.myear}}</h5><br>
                                <h6>{{movie.mdesc}}</h6><br>
                                <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a>
                                <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
                        </div>


        </div>
</div>
{% endblock %}

movieproject/templates/edit.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container" style="padding:10px">
    <div class="row">
        {% for i in movie %}
        <div class="col-md-3">
            <div class="card" style="width: 17.5rem; height: 650px;">
                <img class="card-img-top" src="{{i.mimg.url}}" alt="Card image cap" width="250px" height="250px">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">{{ i.mname }}</h5>
                    <p class="card-text">{{ i.mdesc }}</p>
                    <div class="mt-auto">
                        <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Details</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}